osx_image: xcode11.6
language: swift

xcode_workspace: Parse.xcworkspace
jobs:
    include:
    - stage: Build
      env: iOS
      xcode_scheme: ParseSwift (iOS)
      xcode_destination: platform=iOS Simulator,OS=13.6,name=iPhone 11 Pro Max
    - stage: Build
      env: macOS
      xcode_scheme: ParseSwift (macOS)
      xcode_destination: platform=MacOSX
    - stage: Build
      env: tvOS
      xcode_scheme: ParseSwift (tvOS)
      xcode_destination: platform=AppleTV Simulator,OS=13.4,name=Apple TV
    - stage: Build
      env: watchOS
      xcode_scheme: ParseSwift (watchOS)
      xcode_destination: platform=watchOS Simulator,OS=6.2,name=Apple Watch Series 5 - 44mm

jobs:
  include:
    - stage: Package Managers
      env: Swift Pacakge Manager
      script: 
        - swift build
        - swift test --enable-code-coverage
      after_success:
        - xcrun llvm-cov export -format="lcov" .build/debug/ParseSwiftPackageTests.xctest/Contents/MacOS/ParseSwiftPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
        - bash <(curl https://codecov.io/bash) 
        - gem install jazzy
        - ./Scripts/jazzy.sh
    - stage: Package Managers
      env: Cocoapods
      script: pod lib lint
    - stage: Package Managers
      env: Carthage
      script: carthage build --no-skip-current
