os: osx
osx_image: xcode11.6
language: swift

stage: Build
env:
  matrix:
  - TARGET="ParseSwift (iOS)"
  - TARGET="ParseSwift (macOS)" 
  - TARGET="ParseSwift (tvOS)"
  - TARGET="ParseSwift (watchOS)" 
script: set -o pipefail && xcodebuild -target "$TARGET" | xcpretty

jobs:
  include:
    - stage: Package Managers
      env: Swift Pacakge Manager
      install: bundle install
      script: 
        - swift build
        - swift test --enable-code-coverage --enable-test-discovery
      after_success:
        - xcrun llvm-cov export -format="lcov" .build/debug/ParseSwiftPackageTests.xctest/Contents/MacOS/ParseSwiftPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
        - bash <(curl https://codecov.io/bash) 
        - gem install jazzy
        - ./Scripts/jazzy.sh
    - stage: Package Managers
      env: Cocoapods
      script: pod lib lint
    - stage: Package Managers
      env: Carthage
      script: carthage build --no-skip-current
