version: 2.1

defaults: &defaults
    macos:
      xcode: 11.6.0
    shell: /bin/bash --login -eo pipefail

jobs:
  ios:
    <<: *defaults
    steps:
      - checkout
      - run: xcodebuild -workspace Parse.xcworkspace -scheme ParseSwift\ \(iOS\) -destination platform\=iOS\ Simulator,OS\=13.6,name\=iPhone\ 11\ Pro\ Max build test | xcpretty
      - store_test_results:
          path: build/reports
          
swiftlint:
  docker:
    - image: dantoml/swiftlint:latest
  steps:
    - checkout
    - run: swiftlint lint --reporter junit | tee result.xml
    - store_artifacts:
        path: result.xml
    - store_test_results:
        path: result.xml

workflows:
  build-test-lint:
    jobs:
      - swiftlint
      - ios
