version: 2.1

defaults: &defaults
    macos:
      xcode: 11.6.0
    shell: /bin/bash --login -eo pipefail

aliases:
- &prepare
  |
    HOMEBREW_NO_AUTO_UPDATE=1 brew install swiftlint

jobs:
  ios-build-test:
    <<: *defaults
    steps:
      - checkout
      - run: *prepare
      - run: xcodebuild -workspace Parse.xcworkspace -scheme ParseSwift\ \(iOS\) -destination platform\=iOS\ Simulator,OS\=13.6,name\=iPhone\ 11\ Pro\ Max build test | xcpretty
      - store_test_results:
          path: build/reports
  macos-build:
    <<: *defaults
    steps:
      - checkout
      - run: *prepare
      - run: xcodebuild -workspace Parse.xcworkspace -scheme ParseSwift\ \(macOS\) -destination 'platform=macOS' ONLY_ACTIVE_ARCH=NO | xcpretty
      - store_test_results:
          path: build/reports
  tvos-build:
    <<: *defaults
    steps:
      - checkout
      - run: *prepare
      - run: xcodebuild -workspace Parse.xcworkspace -scheme ParseSwift\ \(tvOS\) -destination 'platform=AppleTV Simulator,OS=13.4,name=Apple TV' ONLY_ACTIVE_ARCH=NO | xcpretty
      - store_test_results:
          path: build/reports
  watchos-build:
    <<: *defaults
    steps:
      - checkout
      - run: *prepare
      - run: xcodebuild -workspace Parse.xcworkspace -scheme ParseSwift\ \(watchOS\) -destination 'platform=watchOS Simulator,OS=6.2,name=Apple Watch Series 5 - 44mm' ONLY_ACTIVE_ARCH=NO | xcpretty
      - store_test_results:
          path: build/reports
  spm-build-test:
    <<: *defaults
    steps:
      - checkout
      - run: *prepare
      - run: swift build
      - run: swift test --enable-code-coverage
      - run: xcrun llvm-cov export -format="lcov" .build/debug/ParseSwiftPackageTests.xctest/Contents/MacOS/ParseSwiftPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
      - run: bash <(curl https://codecov.io/bash)
      - store_test_results:
          path: build/reports
  cocoapods:
    <<: *defaults
    steps:
      - checkout
      - run: *prepare
      - run: pod lib lint
      - store_test_results:
          path: build/reports
  carthage:
    <<: *defaults
    steps:
      - checkout
      - run: *prepare
      - run: carthage build --no-skip-current
      - store_test_results:
          path: build/reports

workflows:
  version: 2.1
  build-test-lint:
    jobs:
      - ios-build-test
      - macos-build:
          requires:
            - ios-build-test
      - tvos-build:
          requires:
            - ios-build-test
      - watchos-build:
          requires:
            - ios-build-test
      - spm-build-test:
          requires:
            - ios-build-test
      - cocoapods:
          requires:
            - spm-build-test
      - carthage:
          requires:
            - spm-build-test
