version: 2.1

defaults: &defaults
    macos:
      xcode: 11.6.0
    shell: /bin/bash --login -eo pipefail

aliases:
- &prepare
  |
    HOMEBREW_NO_AUTO_UPDATE=1 brew install swiftlint

jobs:
  ios-build-test:
    <<: *defaults
    steps:
      - checkout
      - run: *prepare
      - run: xcodebuild -workspace Parse.xcworkspace -scheme ParseSwift\ \(iOS\) -destination platform\=iOS\ Simulator,OS\=13.6,name\=iPhone\ 11\ Pro\ Max build test | xcpretty
      - store_test_results:
          path: build/reports
  macos-build:
    <<: *defaults
    steps:
      - checkout
      - run: *prepare
      - run: xcodebuild -target ParseSwift\ \(macOS\) | xcpretty
      - store_test_results:
          path: build/reports
  tvos-build:
    <<: *defaults
    steps:
      - checkout
      - run: *prepare
      - run: xcodebuild -target ParseSwift\ \(tvOS\) | xcpretty
      - store_test_results:
          path: build/reports
  watchos-build:
    <<: *defaults
    steps:
      - checkout
      - run: *prepare
      - run: xcodebuild -target ParseSwift\ \(watchOS\) | xcpretty
      - store_test_results:
          path: build/reports
  spm-build-test:
    <<: *defaults
    steps:
      - checkout
      - run: *prepare
      - run: swift build
      - run: swift test --enable-code-coverage
      - run: xcrun llvm-cov export -format="lcov" .build/debug/ParseSwiftPackageTests.xctest/Contents/MacOS/ParseSwiftPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
      - run: bash <(curl https://codecov.io/bash)
      - store_test_results:
          path: build/reports
  cocoapods:
    <<: *defaults
    steps:
      - checkout
      - run: *prepare
      - run: pod lib lint
      - store_test_results:
          path: build/reports
  carthage:
    <<: *defaults
    steps:
      - checkout
      - run: *prepare
      - run: carthage build --no-skip-current
      - store_test_results:
          path: build/reports
  docs:
    <<: *defaults
    steps:
      - checkout
      - run: *prepare
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
      - run:
          name: "Install bundler"
          command: |
            sudo gem install bundler
            bundler install --path vendor/bundle
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: ./Scripts/jazzy.sh
      - store_test_results:
          path: build/reports

workflows:
  build-test-lint:
    jobs:
      - ios-build-test
      - macos-build
      - tvos-build
      - watchos-build
      - spm-build-test
      - cocoapods
      - carthage
      - docs
